services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_PASSWORD=password123'
    ports:
      - '5431:5432'
    volumes:
      - './postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './springboot_pg_data:/var/lib/postgresql/data'
