services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=eazy_lyrics'
      - 'POSTGRES_USER=admin_user'
      - 'POSTGRES_PASSWORD=12345'
    ports:
      - '5432:5432'
    volumes:
      - './postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './springboot_pg_data:/var/lib/postgresql/data'
